### ISSUE TITLE
Generate binaries for windows, macos, linux for both amd64 (x64) and arm64

### ISSUE THREAD

**Issue by jaimetur** [Xentraxx/GooglePhotosTakeoutHelper#6]
Modify GitHub Actions to generate binaries for windows, macos, linux for both amd64 (x64) and arm64

This can be done easily with GitHub Actions using a matrix strategic like this:

```
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # os list
        arch: [x86_64, arm64]  # arch list
        exclude:
          - os: windows-latest
            arch: arm64  # Windows is only compiled for x86 (32/64-bit)

    runs-on: ${{ matrix.os }}
```
